# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Generate Metrics
on:
  # Schedule updates (at 00:00)
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  Generating_Metrics:
    runs-on: ubuntu-latest
    steps:
      #base - https://github.com/lowlighter/metrics/blob/master/source/plugins/base/README.md
      - name: base
        uses: lowlighter/metrics@latest
        with:
          filename: Images/Dynamic/base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, repositories, metadata
          plugin_lines: yes
          config_display: large
          repositories_forks: yes
      #languages - https://github.com/lowlighter/metrics/blob/master/source/plugins/languages/README.md
      - name: languages
        uses: lowlighter/metrics@latest
        with:
          filename: Images/Dynamic/languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_colors: ""
          plugin_languages_aliases: ""
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_categories: data, markup, programming, prose
      #notable contributions - https://github.com/lowlighter/metrics/blob/master/source/plugins/notable/README.md
      - name: notable contributions
        uses: lowlighter/metrics@latest
        with:
          filename: Images/Dynamic/contributions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_notable: yes
      #gists - https://github.com/lowlighter/metrics/blob/master/source/plugins/gists/README.md
      - name: gists
        uses: lowlighter/metrics@latest
        with:
          filename: Images/Dynamic/gists.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_gists: yes